---
development:
  publishable_key: <%= ENV.fetch("STRIPE_PUBLISHABLE_KEY", nil) %>
  secret_key: <%= ENV.fetch("STRIPE_SECRET_KEY", nil) %>
  webhook_secret: <%= ENV.fetch("STRIPE_WEBHOOK_SECRET", nil) %>

test:
  publishable_key: <%= ENV.fetch("STRIPE_PUBLISHABLE_KEY", nil) %>
  secret_key: <%= ENV.fetch("STRIPE_SECRET_KEY", nil) %>
  webhook_secret: <%= ENV.fetch("STRIPE_WEBHOOK_SECRET", "whsec_test") %>

production:
  publishable_key: <%= ENV.fetch("STRIPE_PUBLISHABLE_KEY", nil) %>
  secret_key: <%= ENV.fetch("STRIPE_SECRET_KEY", nil) %>
  webhook_secret: <%= ENV.fetch("STRIPE_WEBHOOK_SECRET", nil) %>
